name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "16.13.0"
          - "18.x"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ matrix.node_version }}
      - run: pnpm build
