jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ matrix.node_version }}
      - run: pnpm build
      - run: node ./lib/index.js

    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 18.x
          - 22.x
          - latest
name: Build

on:
  pull_request: ~
  push:
    branches:
      - main
