name: Compliance

on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@main
        with:
          body-auto-close: false
          body-regex: "(fix(es|ed)?|((resolve|close)(s|d)?)) #[1-9]\\d*"
          ignore-authors: |
            renovate
            renovate[bot]
          ignore-team-members: false
