name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - name: Delete branch protection on main
        uses: actions/github-script@v6.4.0
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            try {
              await github.request(
                `DELETE /repos/JoshuaKGoldberg/ts-api-utils/branches/main/protection`,
              );
            } catch (error) {
              if (!error.message?.includes?.("Branch not protected")) {
                throw error;
              }
            }
      - run: echo "SHOULD_RELEASE=$(pnpm run should-semantic-release &> /dev/null && echo '1' || echo '0')"
      - if: ${{ env.SHOULD_RELEASE != '0' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pnpm release-it --verbose
      - if: always()
        name: Recreate branch protection on main
        uses: actions/github-script@v6.4.0
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          # Note: keep this inline script in sync with script/setup.js!
          # Todo: it would be nice to not have two sources of truth...
          # https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/145
          script: |
            github.request(
              `PUT /repos/JoshuaKGoldberg/ts-api-utils/branches/main/protection`,
              {
                allow_deletions: false,
                allow_force_pushes: true,
                allow_fork_pushes: false,
                allow_fork_syncing: true,
                block_creations: false,
                branch: "main",
                enforce_admins: false,
                owner: "JoshuaKGoldberg",
                repo: "ts-api-utils",
                required_conversation_resolution: true,
                required_linear_history: false,
                required_pull_request_reviews: null,
                required_status_checks: {
                  checks: [
                    { context: "build (16.13.0)" },
                    { context: "build (18.x)" },
                    { context: "compliance" },
                    { context: "docs" },
                    { context: "knip" },
                    { context: "lint" },
                    { context: "markdown" },
                    { context: "package" },
                    { context: "packages" },
                    { context: "prettier" },
                    { context: "spelling" },
                    { context: "test (16.13.0, 4.2.4)" },
                    { context: "test (16.13.0, 4.3.5)" },
                    { context: "test (16.13.0, 4.4.4)" },
                    { context: "test (16.13.0, latest)" },
                    { context: "test (18.x, 4.2.4)" },
                    { context: "test (18.x, 4.3.5)" },
                    { context: "test (18.x, 4.4.4)" },
                    { context: "test (18.x, latest)" },
                    { context: "type-check" },
                  ],
                  strict: false,
                },
                restrictions: null,
              }
            );
      - if: ${{ env.SHOULD_RELEASE != '0' }}
        uses: ./.github/workflows/release-docs.yml@main
