name: Release Docs

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  get_old_docs:
    runs-on: ubuntu-latest
    steps:
      - name: get the gh-pages repo
        uses: actions/checkout@v3
        with:
          ref: gh-pages
        continue-on-error: true

      - name: tar the existing docs
        run: |
          mkdir -p ./docs/generated
          tar -cvf old-docs.tar ./docs/generated

      - name: create a document artifact
        uses: actions/upload-artifact@v3
        with:
          name: old-docs
          path: old-docs.tar

  update_and_deploy_docs:
    needs: get_old_docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare

      - run: mkdir -p ./docs/generated
      - name: Download the existing documents artifact
        uses: actions/download-artifact@v3
        with:
          name: old-docs

      - run: tar -xf old-docs.tar ./docs/generated -C ./docs/generated

      - name: Build docs
        run: pnpm run docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/generated

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - run: 'echo "PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: ''{ print $2 }'' | sed ''s/[", ]//g'')" >> $GITHUB_ENV'
      - name: Update Coverage Badge
        run: cp ./docs/generated/v$PACKAGE_VERSION/coverage.svg ./docs/coverage.svg

      - run: echo "COVERAGE_CHANGED=$(git status --porcelain -u | grep -c docs/coverage.svg)" >> $GITHUB_ENV

      - if: ${{ env.COVERAGE_CHANGED != '0' }}
        uses: ./.github/actions/unprotect-main
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - if: ${{ env.COVERAGE_CHANGED != '0' }}
        run: |
          git add docs/coverage.svg
          git commit -m "docs: updated documentation coverage"
          git push

      - if: ${{ always() && env.COVERAGE_CHANGED != '0' }}
        uses: ./.github/actions/protect-main
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
