name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - uses: ./.github/actions/unprotect-main
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - run: echo "SHOULD_RELEASE=$(pnpm run should-semantic-release &> /dev/null && echo '1' || echo '0')" >> $GITHUB_ENV
      - if: ${{ env.SHOULD_RELEASE != '0' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pnpm release-it --verbose
      - if: always()
        uses: ./.github/actions/protect-main
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - if: ${{ env.SHOULD_RELEASE != '0' }}
        uses: ./.github/workflows/release-docs.yml@main
        with:
          push_coverage_changes: true
