jobs:
  resync_protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/unprotect-main
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - uses: ./.github/actions/protect-main
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

name: Resync Protection

on:
  workflow_dispatch: ~
