name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "16.13.0"
          - "18.x"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ matrix.node_version }}
      - run: pnpm run test --coverage
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
