name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "18.x"
          - "16.13.0"
        ts_version:
          - "latest"
          - "4.9.5"
          - "4.6.4"
          - "4.3.5"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ matrix.node_version }}

      - run: pnpm remove typescript
      - run: pnpm add -D typescript@"${{ matrix.ts_version }}"

      - run: pnpm run test --coverage
      - name: Codecov
        uses: codecov/codecov-action@v3
        if: matrix.node_version == '18.x'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flags: ${{ matrix.ts_version }}
